### ISSUE TITLE
Separate torrent download exception

### ISSUE THREAD

**Issue by justscribe** [alanmcgovern/monotorrent#291]
Hi,

For some reason I'm getting error while try to start a second torrent, when the first is already downloading. Version is 1.0.22-master+733ad248.
Stacktrace:
19.04.2020 22:44:14> Value was invalid. | System.ArgumentException: Value was invalid.
   at System.Security.Cryptography.HashAlgorithm.TransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
   at MonoTorrent.Client.DiskManager.<GetHashAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.ReusableTaskAwaiter`1.GetResult()
   at MonoTorrent.Client.Modes.HashingMode.<WaitForHashingToComplete>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoTorrent.Client.TorrentManager.<HashCheckAsync>d__171.MoveNext() | 
19.04.2020 22:44:14> Value was invalid. |

**Comment by OneFingerCodingWarrior** [comment]
to narrow down the issue,  try replace the ReusableTask with Task, and verify the result

**Comment by alanmcgovern** [comment]
@justscribe can you share the two torrents?

**Comment by justscribe** [comment]
1. https://mega.nz/file/woBBEQqL#wOYIGVlUVxZm918Bs_t_dFHB7YTYiLzXgVd33xW-aEc
2. https://mega.nz/file/AlBjTARa#m_KmH6RZmk8NqVgsiQ32-on0O9hz6QO0bI4K_o3kzEo

**Comment by alanmcgovern** [comment]
Can you let me know if this fixes the issue? https://github.com/alanmcgovern/monotorrent/pull/292 ?

If not, can you reproduce with a debug build from that branch? If the issue reproduces can you share the details from the exception so we can tell the offsets, array length, etc from the TransformBlock call which throws an exception? I can't repro your issue locally, but i did find a related problem which *might* be what you're seeing.

**Comment by justscribe** [comment]
Hi,

Thanks, fix is working.
Can't reproduce the issue anymore, and it easly reproduces with previous version.
I also want to mention a more info about reproduce steps.
For every torrent that I've showed you I've used a partial download, file names from each torrent was almost the same (I mean that started download an "animations" folder from both torrents at the same time).

**Comment by alanmcgovern** [comment]
Great. I'll merge that fix and do a release as it's a reasonably bad issue. In practical terms it's unlikely it would be widespread issue as the chances of a conflict for normal random downloading are slim, and if there's a conflict it would cause the piece to redownload. 

Did you only notice this because you had the debugger attached, or did it cause a crash in your app?

**Comment by justscribe** [comment]
Problem reproduces with previous release version in app, not a crash, just an error while try to start seconds torrent. First torrent continues to download, and when download is finished, I freely can start another one. But not together.

**Comment by justscribe** [comment]
More detailed stacktrace (it is a TorrentStateChangedAsync handler):
20.04.2020 21:26:20> Value was invalid. | System.ArgumentException: Value was invalid.
   at System.Security.Cryptography.HashAlgorithm.TransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
   at MonoTorrent.Client.DiskManager.<GetHashAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.ReusableTaskAwaiter`1.GetResult()
   at MonoTorrent.Client.Modes.HashingMode.<WaitForHashingToComplete>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MonoTorrent.Client.TorrentManager.<HashCheckAsync>d__171.MoveNext() | TorrentManager_TorrentStateChangedAsync

**Comment by alanmcgovern** [comment]
When it says the value was invalid can you tell what the values of the parameters are?

Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset

The ones passes to the hash function

**Comment by justscribe** [comment]
inputBuffer = Byte[16416] , inputOffset = 0, inputCount = -13139968, outputBuffer =Byte[16416], outputOffset = 0.

**Comment by alanmcgovern** [comment]
Perfect! Thanks for that. that gives me the information I need to ensure the bug is fixed. I'll review things later today, but that is exactly the kind of issue which should be resolved now :)

**Comment by justscribe** [comment]
Thank you for help.
