### ISSUE TITLE
Multiple NullReferenceException exceptions in PeerMessage.cs while in Metadata mode

### ISSUE THREAD

**Issue by vlasenkoalexey** [alanmcgovern/monotorrent#302]
I noticed that there are multiple exceptions are thrown for the following line in Metadata mode:
Register (BitfieldMessage.MessageId, data => new BitfieldMessage ((int) Math.Ceiling ((double)
 data.Size / data.PieceLength)));

The stacktrace is following:
   at System.Environment.get_StackTrace()
   at System.Runtime.CompilerServices.ReusableTaskAwaiter`1.GetResult()
   at MonoTorrent.Client.ConnectionManager.ReceiveMessagesAsync(IConnection2 connection, IEncryption decryptor, RateLimiterGroup downloadLimiter, ConnectionMonitor monitor, TorrentManager torrentManager, PeerId id)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.<>c.<.cctor>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Runtime.CompilerServices.ResultHolder.<>c.<.cctor>b__4_0(Object state)
   at MonoTorrent.Client.MainLoop.Loop()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

   System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MonoTorrent
  StackTrace:
   at MonoTorrent.Client.Messages.PeerMessage.<>c.<.cctor>b__1_1(ITorrentData data) in C:\Projects\_TorrentRT\monotorrent\src\MonoTorrent\MonoTorrent.Client.Messages\PeerMessage.cs:line 52
   at MonoTorrent.Client.Messages.PeerMessage.DecodeMessage(Byte[] buffer, Int32 offset, Int32 count, ITorrentData manager) in C:\Projects\_TorrentRT\monotorrent\src\MonoTorrent\MonoTorrent.Client.Messages\PeerMessage.cs:line 100
   at MonoTorrent.Client.PeerIO.<ReceiveMessageAsync>d__3.MoveNext() in C:\Projects\_TorrentRT\monotorrent\src\MonoTorrent\MonoTorrent.Client\PeerIO.cs:line 115
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:   MonoTorrent.Client.Messages.PeerMessage..cctor.AnonymousMethod__1_1(MonoTorrent.ITorrentData) in PeerMessage.cs
    MonoTorrent.Client.Messages.PeerMessage.DecodeMessage(byte[], int, int, MonoTorrent.ITorrentData) in PeerMessage.cs
    MonoTorrent.Client.PeerIO.ReceiveMessageAsync(MonoTorrent.Client.Connections.IConnection2, MonoTorrent.Client.Encryption.IEncryption, MonoTorrent.Client.RateLimiters.IRateLimiter, MonoTorrent.Client.ConnectionMonitor, MonoTorrent.Client.ConnectionMonitor, MonoTorrent.ITorrentData) in PeerIO.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

For current logic torrentManager.Torrent is always null for Metadata mode, and socket is going to be cleared in ConnectionManager.ReceiveMessagesAsync

Does it make sense to clear socket and close connection in such case?
Is this a correct logic?
Would it be possible to use BitfieldMessage while in Metadata mode?
For some reason DHT discovery doesn't work that well for MonoTorrent, could this be related?

**Comment by alanmcgovern** [comment]
That's a good call! The tests didn't cover this.

I have a test covering this and will figure out a good approach for this soon: https://github.com/alanmcgovern/monotorrent/pull/new/bitfield-metadata-mode

**Comment by alanmcgovern** [comment]
` For some reason DHT discovery doesn't work that well for MonoTorrent, could this be related?`

Maybe? If Dht is finding peers but MonoTorrent is disconnecting from them, then this could be the reason alright. If this is the issue you were seeing, that should be fixed in master now.

If MonoTorrent is *not* finding peers then either there's a bug in the Dht code, or there's a slow bootstrapping issue (or similar). If this is the case, then please open a new issue and we can look into the Dht problem in more detail :)
