### ISSUE TITLE
HashCheckAsync find some failed hashes on a V1only torrent that was fully downloaded a second ago

### ISSUE THREAD

**Issue by ManlyMarco** [alanmcgovern/monotorrent#632]
1 - Grab a torrent file for a partially or fully downloaded torrent.
2 - Hash check, some of the existing files fail the hash check.
3 - Start the torrent and download the failed files.
4 - Once download completes, stop the torrent and dispose the client. The files are correctly downloaded on the disk.
5 - Repeat 1 for the same torrent.
6 - The files fail the hash check again, despite having been correctly downloaded (which files fail can differ, but it seems like it's always the same ones no matter the current completion when hashing)

Tested on latest master build on both the seed / torrent creator and the client.

I tried switching to V2only torrents but that failed with exception, I guess that would be a separate issue:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MonoTorrent.Client.DiskManager.IncrementalHashData.AppendData(ReadOnlySpan`1 buffer)
   at MonoTorrent.Client.DiskManager.GetHashAsync(ITorrentManagerInfo manager, Int32 pieceIndex, PieceHash dest)
   at MonoTorrent.Client.DiskManager.GetHashAsync(ITorrentManagerInfo manager, Int32 pieceIndex, PieceHash dest)
   at System.Runtime.CompilerServices.ReusableTaskAwaiter`1.GetResult()
   at MonoTorrent.TorrentCreator.CalcPiecesHash(ITorrentManagerInfo manager, CancellationToken token)
   at MonoTorrent.TorrentCreator.CreateAsync(String name, ITorrentFileSource fileSource, CancellationToken token)
   at MonoTorrent.TorrentCreator.CreateAsync(ITorrentFileSource fileSource, CancellationToken token)
   at MonoTorrent.TorrentCreator.CreateAsync(ITorrentFileSource fileSource, String savePath, CancellationToken token)
   at MonoTorrent.TorrentCreator.Create(ITorrentFileSource fileSource, String savePath)
   at Program.<Main>$(String[] args) in D:\SVN\ManlyMarco\testfield\KKM_Serverside\Program.cs:line 217
   ```

I have no idea how to give any useful info on this, it only happens on some torrents and it seems like it's always the same files. Let me know if I can maybe add any logging that would be useful. Worst case we could coordinate on discord so you could test  on a live system and actual torrents.

Edit: Could it have anything to do with case sensitivity? Clients can have filenames in a different case from the server that generates the torrent file. The server can also have two folders with same name but different case, but the client is always case-insensitive.
Edit2: It looks like one of the torrents has this issue even without the case differences. Could it be some special characters like `Ω` in folder and file names instead? Files without the special characters are affected too.
Edit3: Hmm, two of the files that are affected by this bug are showing `file.BitField.PercentComplete` being equal to `50` (the files exist on disk) while some other files that exist on disk are reported as `0`. (in the screenshot below the left number is `PercentComplete * 100` so divide that by 100, right number is the actual file completion %)
![image](https://user-images.githubusercontent.com/39247311/219535526-290b7b05-0d61-422e-9a0e-1cd5608dc930.png)

**Comment by ManlyMarco** [comment]
I found the issue, using MoveFileAsync twice on a file while the torrent was running somehow caused some files to get lost. Not sure if it's a bug in the library or in my code, but it got resolved after removing all but one MoveFileAsync calls and making sure that the file isn't already in the location that I'm trying to move it to (I think trying to move to the same location is a possible cause).
